// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rtsp_sender.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Connect Request from client
type ConnectRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ConnectClientAddress string   `protobuf:"bytes,2,opt,name=connectClientAddress,proto3" json:"connectClientAddress,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	EnableRTSPRelay      bool     `protobuf:"varint,5,opt,name=enableRTSPRelay,proto3" json:"enableRTSPRelay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f361b3a5b5b7561b, []int{0}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ConnectRequest) GetConnectClientAddress() string {
	if m != nil {
		return m.ConnectClientAddress
	}
	return ""
}

func (m *ConnectRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConnectRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ConnectRequest) GetEnableRTSPRelay() bool {
	if m != nil {
		return m.EnableRTSPRelay
	}
	return false
}

type ConnectReplyData struct {
	RelayAddress         string   `protobuf:"bytes,1,opt,name=relayAddress,proto3" json:"relayAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReplyData) Reset()         { *m = ConnectReplyData{} }
func (m *ConnectReplyData) String() string { return proto.CompactTextString(m) }
func (*ConnectReplyData) ProtoMessage()    {}
func (*ConnectReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f361b3a5b5b7561b, []int{1}
}

func (m *ConnectReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReplyData.Unmarshal(m, b)
}
func (m *ConnectReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReplyData.Marshal(b, m, deterministic)
}
func (m *ConnectReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReplyData.Merge(m, src)
}
func (m *ConnectReplyData) XXX_Size() int {
	return xxx_messageInfo_ConnectReplyData.Size(m)
}
func (m *ConnectReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReplyData proto.InternalMessageInfo

func (m *ConnectReplyData) GetRelayAddress() string {
	if m != nil {
		return m.RelayAddress
	}
	return ""
}

// Connect Reply from server
type ConnectReply struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ConnectReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConnectReply) Reset()         { *m = ConnectReply{} }
func (m *ConnectReply) String() string { return proto.CompactTextString(m) }
func (*ConnectReply) ProtoMessage()    {}
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f361b3a5b5b7561b, []int{2}
}

func (m *ConnectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReply.Unmarshal(m, b)
}
func (m *ConnectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReply.Marshal(b, m, deterministic)
}
func (m *ConnectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReply.Merge(m, src)
}
func (m *ConnectReply) XXX_Size() int {
	return xxx_messageInfo_ConnectReply.Size(m)
}
func (m *ConnectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReply proto.InternalMessageInfo

func (m *ConnectReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ConnectReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConnectReply) GetData() *ConnectReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

// Disconnect Request from client
type DisconnectRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ConnectClientAddress string   `protobuf:"bytes,2,opt,name=connectClientAddress,proto3" json:"connectClientAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f361b3a5b5b7561b, []int{3}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *DisconnectRequest) GetConnectClientAddress() string {
	if m != nil {
		return m.ConnectClientAddress
	}
	return ""
}

// Disconnect Reply from server
type DisconnectReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReply) Reset()         { *m = DisconnectReply{} }
func (m *DisconnectReply) String() string { return proto.CompactTextString(m) }
func (*DisconnectReply) ProtoMessage()    {}
func (*DisconnectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f361b3a5b5b7561b, []int{4}
}

func (m *DisconnectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReply.Unmarshal(m, b)
}
func (m *DisconnectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReply.Marshal(b, m, deterministic)
}
func (m *DisconnectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReply.Merge(m, src)
}
func (m *DisconnectReply) XXX_Size() int {
	return xxx_messageInfo_DisconnectReply.Size(m)
}
func (m *DisconnectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReply.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReply proto.InternalMessageInfo

func (m *DisconnectReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DisconnectReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "ConnectRequest")
	proto.RegisterType((*ConnectReplyData)(nil), "ConnectReplyData")
	proto.RegisterType((*ConnectReply)(nil), "ConnectReply")
	proto.RegisterType((*DisconnectRequest)(nil), "DisconnectRequest")
	proto.RegisterType((*DisconnectReply)(nil), "DisconnectReply")
}

func init() {
	proto.RegisterFile("rtsp_sender.proto", fileDescriptor_f361b3a5b5b7561b)
}

var fileDescriptor_f361b3a5b5b7561b = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xc1, 0x4f, 0xea, 0x40,
	0x10, 0xc6, 0xe9, 0x7b, 0xf0, 0xe0, 0xcd, 0xe3, 0x09, 0x6c, 0x3c, 0x34, 0x9c, 0xc8, 0x26, 0x26,
	0x24, 0x86, 0x36, 0x41, 0x43, 0xbc, 0x19, 0x85, 0x8b, 0x37, 0x53, 0x3c, 0x79, 0x31, 0xcb, 0x76,
	0xd2, 0x36, 0xb6, 0xbb, 0x75, 0x77, 0xab, 0xf2, 0xef, 0xf9, 0x97, 0x99, 0x6e, 0x29, 0x02, 0x7a,
	0xf1, 0xe0, 0xad, 0xdf, 0x7c, 0xd3, 0x9d, 0xf9, 0x4d, 0x3e, 0x18, 0x28, 0xa3, 0xf3, 0x07, 0x8d,
	0x22, 0x44, 0xe5, 0xe5, 0x4a, 0x1a, 0x49, 0xdf, 0x1c, 0x38, 0x9a, 0x4b, 0x21, 0x90, 0x9b, 0x00,
	0x9f, 0x0a, 0xd4, 0x86, 0x0c, 0xa1, 0xc3, 0xd3, 0x04, 0x85, 0xb9, 0x59, 0xb8, 0xce, 0xc8, 0x19,
	0xff, 0x0d, 0xb6, 0x9a, 0x4c, 0xe1, 0x98, 0x57, 0xdd, 0x73, 0x5b, 0xba, 0x0a, 0x43, 0x85, 0x5a,
	0xbb, 0xbf, 0x6c, 0xdf, 0x97, 0x5e, 0xf9, 0x5e, 0xa1, 0x51, 0x09, 0x96, 0xa1, 0xfb, 0xbb, 0x7a,
	0xaf, 0xd6, 0xa5, 0x97, 0x33, 0xad, 0x5f, 0xa4, 0x0a, 0xdd, 0x66, 0xe5, 0xd5, 0x9a, 0x8c, 0xa1,
	0x87, 0x82, 0xad, 0x52, 0x0c, 0xee, 0x96, 0xb7, 0x01, 0xa6, 0x6c, 0xed, 0xb6, 0x46, 0xce, 0xb8,
	0x13, 0x1c, 0x96, 0xe9, 0x0c, 0xfa, 0x5b, 0x86, 0x3c, 0x5d, 0x2f, 0x98, 0x61, 0x84, 0x42, 0x57,
	0x95, 0x66, 0xbd, 0x61, 0x45, 0xb2, 0x57, 0xa3, 0x1c, 0xba, 0xbb, 0xff, 0x11, 0x02, 0x4d, 0x2e,
	0x43, 0xb4, 0xbd, 0xad, 0xc0, 0x7e, 0x13, 0x17, 0xda, 0x19, 0x6a, 0xcd, 0x22, 0xdc, 0x40, 0xd6,
	0x92, 0x9c, 0x40, 0x33, 0x64, 0x86, 0x59, 0xa6, 0x7f, 0xd3, 0x81, 0x77, 0xb8, 0x42, 0x60, 0x6d,
	0xca, 0x61, 0xb0, 0x48, 0x34, 0xff, 0xd1, 0x1b, 0xd3, 0x4b, 0xe8, 0xed, 0x0e, 0xf9, 0x36, 0xcc,
	0x54, 0x02, 0x94, 0xf7, 0x5c, 0xda, 0x6c, 0x90, 0x53, 0x68, 0x6f, 0x68, 0x48, 0xcf, 0xdb, 0x8f,
	0xc7, 0xf0, 0xff, 0x1e, 0x28, 0x6d, 0x90, 0x73, 0x80, 0x8f, 0xd9, 0x84, 0x78, 0x9f, 0x68, 0x87,
	0x7d, 0xef, 0x60, 0x39, 0xda, 0xb8, 0xbe, 0xb8, 0x9f, 0x45, 0x89, 0x89, 0x8b, 0x95, 0xc7, 0x65,
	0xe6, 0x87, 0xcc, 0xc4, 0x66, 0xf6, 0x2c, 0x22, 0x3f, 0xe6, 0x59, 0x61, 0x26, 0x26, 0xc6, 0xd7,
	0x44, 0xfb, 0x65, 0x5e, 0x27, 0x55, 0x5e, 0xfd, 0xfc, 0x31, 0xf2, 0x23, 0x95, 0xf3, 0xd5, 0x1f,
	0x9b, 0xdc, 0xb3, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xe2, 0x64, 0x23, 0xce, 0x02, 0x00,
	0x00,
}
