version: "3.98"
services:

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  message-broker-server:
    build:
      context: message-broker-server
      dockerfile: Dockerfile
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 1883:1883
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  node-api-server:
    build:
      context: node-api-server
      dockerfile: Dockerfile
    environment:
      - BROKER_HOST=rabbitmq
    volumes:
      - ./node-api-server:/usr/app
      - api_node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: >
      sh -c "npm run dev"
    restart: always
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      - message-broker-server
      - mongodb

  node-api-gateway:
    build:
      context: node-api-gateway
      dockerfile: Dockerfile
    # environment:
    #   - BROKER_HOST=rabbitmq
    volumes:
      - ./node-api-gateway:/usr/app
      - gateway_node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: >
      sh -c "npm run dev"
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - node-api-server

volumes:
  api_node_modules:
  gateway_node_modules:
  mongodb_data:
