version: "3.98"
services:
  # server:
    # image: node:alpine
    # volumes:
    #   - ./node-api-server:/service/node-api-server
    # working_dir: /service/node-api-server
    # command: >
    #   sh -c "node cmd/server/main.js"
    # restart: always
    # ports:
    #   - "8080:8080"
  
  sfu:
    image: golang:alpine
    volumes:
      - ./ion-sfu:/service/ion-sfu
      - ./ion-sfu/config.toml:/configs/sfu.toml
    working_dir: /service/ion-sfu
    restart: always
    command: >
      sh -c "go run ./cmd/signal/allrpc/main.go -c /configs/sfu.toml"
    environment:
      - gaddr=:5551
      - jaddr=:7000
    ports:
      - 7000:7000
      - 5551:5551
      - 5000-5300:5000-5300/udp
    networks:
      - ionnet 
    
  rtsp-sender:
    build:
      dockerfile: ./rtsp_sender/Dockerfile.local
      context: .
    volumes:
      - ./rtsp_sender:/service/rtsp_sender
      - ./rtsp_sender/config.toml:/configs/rtsp_sender.toml
    working_dir: /service/rtsp_sender
    restart: always
    command: >
      sh -c "go run ./cmd/rtsp_sender/main.go -c /configs/rtsp_sender.toml"
    ports:
      - 8554:8554
      # - 5551:5551
      # - 5000-5300:5000-5300/udp
    environment:
    - GST_DEBUG=1

networks:
  ionnet:
