version: "3.98"
services:
  server:
    # image: node:alpine
    build:
      context: .
    volumes:
      - .:/service/app/server/
      - node_api_modules:/service/app/server/node_modules
    working_dir: /service/app/server/
    command: >
      sh -c "npm run start"

    restart: unless-stopped

    ports:
      - "3000:3000"
volumes:
  node_api_modules:

