[sfu]
sfu_address = "127.0.0.1:5551"

[rtsp_sender]

[rtsp_sender.grpc]
port = "5551"

[rtsp_sender.rtsp_relay]
rtsp_relay_server_path = "/configs"
rtsp_relay_server_config_path = "/configs/rtsp-simple-server.yml"
rtsp_relay_ip = "127.0.0.1" # Don't use localhost
rtsp_relay_port = "8554" # Port for RTSP Server is configured in pkg/rtsp_server_sdk

[log]
level = "info"
filePath= "logs/rtsp_sender.log"
maxSize=50
maxBackups=10
maxAge=28

[network]
max_bitrate = "1000"
min_bitrate = "50"
twcc_interval = "100" #Miliseconds